BEGIN TRANSACTION;
CREATE TABLE AppSummary (DrunkWordListID NUMERIC, EmotionalWordListID NUMERIC, GameMatrixID NUMERIC, Current NUMERIC, InstallDate NUMERIC, Version TEXT);
CREATE TABLE DoseageLog (DoseageFinish NUMERIC, DoseageStart NUMERIC, ExitCode TEXT, ID INTEGER PRIMARY KEY, Pints NUMERIC, SessionID NUMERIC, SessionStart NUMERIC, Spirits NUMERIC, Wine NUMERIC);
CREATE TABLE DrunkWordList (DrunkFactor NUMERIC, DrunkLIstID NUMERIC, Frequency NUMERIC, Pissonym TEXT);
CREATE TABLE EmotionalWordLists (ArousalMean NUMERIC, ArousalSD NUMERIC, Category TEXT, DominaceSD NUMERIC, DominanceMean NUMERIC, Frequency NUMERIC, ValenceMean NUMERIC, ValenceSD NUMERIC, Weight NUMERIC, Word TEXT, WordID NUMERIC, WordListID NUMERIC);
CREATE TABLE EmotionalWordSummary (Coordination_GO NUMERIC, Coordination_NOGO NUMERIC, EmotionalWordsFinish NUMERIC, EmotionalWordsStart NUMERIC, ID INTEGER PRIMARY KEY, ReactionTime_GO NUMERIC, ReactionTIme_NOGO NUMERIC, WordList TEXT);
CREATE TABLE RecallTestSummary (Accuracy_GO NUMERIC, Accuracy_NOGO NUMERIC, Coordination_GO NUMERIC, Coordination_NOGO NUMERIC, Errors_GO NUMERIC, Errors_NOGO NUMERIC, ID INTEGER PRIMARY KEY, MemoryTestFinish NUMERIC, MemoryTestStart NUMERIC, ReactionTime_GO NUMERIC, ReactionTime_NOGO NUMERIC);
CREATE TABLE RecogniseTestSummary (Accuracy_GO NUMERIC, Accuracy_NOGO NUMERIC, Coordination_GO NUMERIC, Coordination_NOGO NUMERIC, Errors_GO NUMERIC, Errors_NOGO NUMERIC, ID INTEGER PRIMARY KEY, MemoryTestFinish NUMERIC, MemoryTestStart NUMERIC, ReactionTime_GO NUMERIC, ReactionTime_NOGO NUMERIC);
CREATE TABLE OnePlaySummary (AppFinished NUMERIC, AppLaunched NUMERIC, AppVersion TEXT, DoseageID NUMERIC, EmotionalWordID NUMERIC, GameID NUMERIC, ID INTEGER PRIMARY KEY, SelfAssessmentID NUMERIC, SummaryID NUMERIC);
CREATE TABLE PersonalInfo (Age NUMERIC, Height NUMERIC, HeightUnits NUMERIC, ID NUMERIC, Nickname TEXT, PrivacyLevel NUMERIC, ServerGUID TEXT, Weight NUMERIC, WeightUnits NUMERIC);
CREATE TABLE SelfAssessment (DrunkBlur NUMERIC, Drunkeness NUMERIC, Energy NUMERIC, EnergyBlur NUMERIC, Happiness NUMERIC, HappyBlur NUMERIC, ID INTEGER PRIMARY KEY, SelfAssessmentFinish NUMERIC, SelfAssessmentStart NUMERIC);
CREATE TABLE StatLearnMatrices (FinishObject NUMERIC, GameMatrixID NUMERIC, StartObject NUMERIC, TransitionProbability NUMERIC);
CREATE TABLE StatLearnSummary (Errors_GO NUMERIC, Errors_NOGO NUMERIC, GameDuration NUMERIC, GameFinish NUMERIC, GameStart NUMERIC, Hits_GO NUMERIC, Hits_NOGO NUMERIC, ID INTEGER PRIMARY KEY, Level NUMERIC, ReactionTimeGO NUMERIC, ReactionTimeNOGO NUMERIC, TotalScore NUMERIC);
CREATE TABLE SummaryID (AccuracyScore NUMERIC, CoordinationScore NUMERIC, DrunkPicture NUMERIC, DrunkRating NUMERIC, DrunkWord TEXT, FinalScore NUMERIC, ID INTEGER PRIMARY KEY, InhibitionScore NUMERIC, MemoryScore NUMERIC, SpeedScore NUMERIC, SummaryFInish NUMERIC, SummaryStart NUMERIC);
CREATE TABLE UsageLog (Action TEXT, Message TEXT, OpenCount NUMERIC, TimeStamp NUMERIC);
COMMIT;
